### ISSUE TITLE
AIs with AK civilizations don't have names.

### ISSUE THREAD

**Issue by Jineapple** [Tails8521/WololoKingdoms#2]
If you're playing against an AI who is playing as one the African Kingdom civs they will have empty names, this should be the case because the language.ini file is missing available "leaders" to choose from.
Currently these leaders have IDs of the format 106xxx, it should be just 6xxx, then it should work (did for me in a short test)

**Comment by Tails8521** [comment]
I'll look into that for the next release, another issue I've noticed is leader names with non-english characters (the Magyar ones for example), and more generally every non-english characters converted from the language file.

**Comment by Jineapple** [comment]
I think you currently have the .ini file as UTF-8 but it needs to be ANSI for the game to read it properly.
