### ISSUE TITLE
Steam API couldn't be initialized

### ISSUE THREAD

**Issue by florianjehn** [Tails8521/WololoKingdoms#21]
Hello there,
thank you for your great tool!
Sadly I have a little problem with it. Wololo Kingdoms does not realize steam is open and only gives me "Steam API couldn't be initialized" as error message. Is this a bug or a problem on my part?
Cheers

**Comment by Jineapple** [comment]
This is still somewhat of an open issue. Some people with it have been able to fix it, but not others. See here: https://github.com/Jineapple/WololoKingdoms/issues/27

**Comment by florianjehn** [comment]
Works for me now. Both Steam and Wololo Kingdoms have to be run as Admin (Win10)
