### ISSUE TITLE
Can't read empires2_x1_p1.dat

### ISSUE THREAD

**Issue by AjajpAlejandro** [Tails8521/WololoKingdoms#3]
When I launch WololoKingdoms.exe, a CMD window appears saying that it cannot read "...resources/_common/dat/empires2_x1_p1.dat". Is there a fix to this? Thanks in advance.

**Comment by Tails8521** [comment]
Where is WololoKingdoms.exe located ?

**Comment by AjajpAlejandro** [comment]
In .../Steam/SteamApps/common/Age2HD/

**Comment by Tails8521** [comment]
It needs to be like this: 
.../SteamApps/common/Age2HD/WololoKingdoms/WololoKingdoms.exe

**Comment by AjajpAlejandro** [comment]
Hmmmm, that makes sense, thanks! I will try it out and see how it goes. Thanks again for the quick response!
EDIT: Yeah, it works. Thanks!
