### ISSUE TITLE
Ludakris map

### ISSUE THREAD

**Issue by warenhuis** [Tails8521/WololoKingdoms#9]
First of all, great stuff!

I wonder however, why the ludakris map isn't available (on Voobly, that is)? Would it be possible to implement this in the next release?

**Comment by Tails8521** [comment]
The original AOC engine doesn't support it, even with userpatch. Even if it would, it wouldn't work really well performance-wise with the pathfinding algorithms used in the game (just look how unplayable these maps are in HD once there's a few units moving on the map)
